#
# Copyright 2021 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uf
  name: splunk-uf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uf
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: uf
    spec:
      initContainers:
      - name: copy-addon-to-container
        image: ubuntu:latest
        command:
        - /bin/sh
        args:
        - -c
        - |
          ls -al;
          apt update && apt upgrade -y;
          apt install wget -y;
          wget "http://nginx:80/$ADDON_LOCATION";
          tar xzvf $SPLUNK_ADDON --directory /ufaddon/;
          ls -al /ufaddon/;
        volumeMounts:
        - mountPath: /ufaddon
          name: ufaddon
        - mountPath: /uf-files
          name: uf-files
      containers:
      - name: uf
        env:
        - name: SPLUNKBASE_USERNAME
          value: admin
        - name: SPLUNK_PASSWORD
          value: Chang3d!
        - name: SPLUNK_START_ARGS
          value: --accept-license
        image: splunk/universalforwarder:latest
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 8089
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - cat /opt/container_artifact/ansible.log | grep "PLAY RECAP"
          failureThreshold: 15
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 750m
            memory: 4Gi
        volumeMounts:
        - mountPath: /opt/splunkforwarder/etc/apps/
          name: ufaddon
        - mountPath: /$TEST_RUNNER_DIRECTORY_UF/uf_files/
          name: uf-files
      volumes:
      - emptyDir: {}
        name: ufaddon
      - emptyDir: {}
        name: uf-files